pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS = credentials('dockerhub')
    }

    stages {

        stage('Clone Repo') {
            steps {
                checkout scm
                sh 'ls -la'
            }
        }

        stage('Build Image') {
            steps {
                sh 'docker build -t dockercorona/jenkinstest:$BUILD_NUMBER ./pushdockerimage/'
            }
        }

        stage('Docker Login') {
            steps {
                sh 'echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin'
            }
        }

        stage('Docker Push') {
            steps {
                sh 'docker push dockercorona/jenkinstest:$BUILD_NUMBER'
            }
        }
    }

    post {
        always {
            sh 'docker logout || true'
        }
    }
}
